name: wrapper
on: [push, pull_request]

jobs:
  validation:
    name: Validate gradle wrapper
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: gradle/wrapper-validation-action@v3